export const LOGIN_ENDPOINT = "http://localhost:8080/login"
export const LOGOUT_ENDPOINT = "http://localhost:8080/logout"
export const CHECK_AUTHENTICATED = "http://localhost:8080/current-user/authenticated"
export const ALL_USER_NOTES_LIST = "http://localhost:8080/notes"
export const SINGLE_USER_NOTE = "http://localhost:8080/notes"
export const ALL_PUBLISHED_NOTES_LIST = "http://localhost:8080/notes/published/all"
export const CURRENT_USER = "http://localhost:8080/current-user/data"
export const ADD_NOTE_ENDPOINT = "http://localhost:8080/notes"

export const DELETE_ENDPOINT = "http://localhost:8080/notes"
export const UPDATE_ENDPOINT = "http://localhost:8080/notes"
export const PUBLISH_ENDPOINT = "http://localhost:8080/notes/publish"
export const UNPUBLISH_ENDPOINT = "http://localhost:8080/notes/unpublish"

export const UPDATE_USER_DATA_ENDPOINT = "http://localhost:8080/current-user/update-data"
export const UPDATE_USER_PASSWORD_ENDPOINT = "http://localhost:8080/current-user/update-password"
